version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-postgres.sh", "postgres", "mix", "phx.server"]
    environment:
      - DB_HOSTNAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:11.5
    volumes:
      - "./volumes:/var/lib/postgresql/data"
    ports: 
      - "5432:5432"
  redis:
    image: redis
